### ISSUE TITLE
tsconfig paths not resolved with documented setup instructions

### ISSUE THREAD

**Issue by benedictleejh** [nuxt/test-utils#1408]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.19.1
- Nuxt Version:     4.1.1
- CLI Version:      3.28.0
- Nitro Version:    2.12.5
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      compatibilityDate, devtools, modules, typescript
- Runtime Modules:  @nuxt/test-utils/module@3.19.2
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/nuxt-starter-yt6qbe2t

### Describe the bug

In the setup instructions from https://nuxt.com/docs/4.x/getting-started/testing#setup, tsconfig aliases are no longer resolved as Vitest does not resolve tsconfig paths by default. In the reproduction, simply running `pnpm nuxt test` will result in the error `Error: Cannot find module '~/utils/add'`.

The older `defineVitestConfig` added the necessary Nuxt alias resolutions by default, as does the new `defineVitestProject`, but the recommended project config for non-`nuxt` environment tests does not have the necessary resolutions for aliases to work. This complicates the process for users migrating from `defineVitestConfig` to `defineVitestProject`, and results in unintuitive errors for new users who prefer/use aliases over relative paths (e.g. for readability reasons).

Some possible solutions to this issue:
1. Document the need to copy relevant tsconfig paths from the generated Nuxt tsconfig to `vitest.config.ts`
a. I would recommend against this solution as it is repeating information that is already stored somewhere else, and doubles the work of setting up extra tsconfig aliases if people need it in their tests
2. Recommend that people add `vite-tsconfig-paths` to their setup to get access to their tsconfig paths in their tests
a. _Edit_: I have been playing with this for about half a day, and I can't get this to work. If anyone manages to figure out how to make `vite-tsconfig-paths` work with Nuxt 4's solution-style tsconfig, do let me know.
4. Provide a way for users to generate Vitest projects with the necessary resolutions in projects where the environment is not `nuxt`, e.g. extending `defineVitestProject` to handle non-`nuxt` environments

### Logs

```shell-script

```

**Comment by wattanx** [comment]
I came up with a workaround: reuse `resolve.alias` by using `defineVitestConfig`.

https://stackblitz.com/edit/github-nkykjsfc

```ts
import { defineVitestProject } from '@nuxt/test-utils/config';
import { defineConfig, defineProject } from 'vitest/config';
import type { TestProjectConfiguration } from 'vitest/config';

async function defineTestProjects(): Promise<TestProjectConfiguration[]> {
  const nuxtProject = await defineVitestProject({
    test: {
      name: 'nuxt',
      environment: 'nuxt',
      include: ['**/*.nuxt.spec.ts'],
    },
  });

  return [
    nuxtProject,
    defineProject({
      resolve: nuxtProject.resolve,
      test: {
        name: 'unit',
        environment: 'node',
        include: ['**/*.spec.ts'],
        exclude: ['**/*.nuxt.spec.ts', 'node_modules'],
      },
    }),
  ];
}

export default defineConfig({
  test: {
    projects: await defineTestProjects(),
  },
});

```

**Comment by danielroe** [comment]
this is now resolved for nuxt tests (in `nuxt/` directory) - see https://github.com/nuxt/nuxt/pull/33672.

**Comment by benedictleejh** [comment]
https://github.com/nuxt/nuxt/pull/33672 only adds the test files to the TypeScript context, and the aliases are still not being passed to Vitest, so the tests still fail with the same error. The reproduction has been updated to Nuxt 4.3.0, and the same error is still happening. Could this issue be reopened until we do not need a workaround to pass the aliases to Vitest?

Reproduction: https://stackblitz.com/edit/nuxt-starter-yt6qbe2t
