### ISSUE TITLE
Using `mountSuspended()` with a component using `<script setup>` and `#import` makes an error

### ISSUE THREAD

**Issue by cadenzah** [nuxt/test-utils#871]
### Environment

Working directory: /home/projects/jvmibwmjx.github
Nuxt project info:

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.2
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  yarn@1.22.19
- Builder:          -
- User Config:      devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

https://stackblitz.com/edit/github-mmtufx?file=app.vue

### Describe the bug

Let's say there is a root component which I want to mount using `@nuxt/test-utils`'s `mountSuspended()` API. If this component

- uses `<script setup>`
- imports composable API from Nuxt `#import` (i.e. `useRouter`, `useRoute`, ...)

it makes an error below and breaks entire test.

```bash
stdout | createSuspenseBoundary (/home/projects/jvmibwmjx.github/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1451:43)
<Suspense> is an experimental feature and its API will likely change.

stderr | warn$1 (/home/projects/jvmibwmjx.github/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:50:13)
[Vue warn]: Cannot mutate <script setup> binding "useRouter" from Options API. 
  at <MountSuspendedComponent > 
  at <MountSuspendedHelper> 
  at <Anonymous ref="VTU_COMPONENT" > 
  at <VTUROOT>
[Vue warn]: Unhandled error during execution of render function 
  at <MountSuspendedComponent > 
  at <MountSuspendedHelper> 
  at <Anonymous ref="VTU_COMPONENT" > 
  at <VTUROOT>
```

Only if the root component meets the condition above, the issue occurs. As you see in the reproduction, if you use `#imports` and `<script setup>` in child elements it work fine.

The app itself is built and works fine if I run it.

You can reproduce the issue with the repository link above.

**Comment by Aietes** [comment]
Is there any update on this? I'm getting a very similar error in my tests, and the workaround above does not seem feasible to be included in a simple test.

**Comment by ngajhede** [comment]
I am running into the same issue. It's the only component/test running into this, despite all of them using `<script setup lang="ts">`.

```ts
<script lang="ts" setup>
const {
  label,
  error,
  helpText,
  id = 'input',
} = defineProps<{
  label?: string;
  error?: string;
  helpText?: string;
  id?: string;
}>();
const modelValue = defineModel<string | number>();
const attrs = useAttrs();
</script>
````

`[Vue warn]: Cannot mutate <script setup> binding "error" from Options API.`

**Comment by cadenzah** [comment]
Possibly the same issue as #744? Any updates for this or that?
@danielroe

**Comment by oskarols** [comment]
Related bug report: https://github.com/nuxt/test-utils/issues/986

@ngajhede In your case it's breaking since you're using the prop name `error`.

**Comment by danielroe** [comment]
resolved in https://github.com/nuxt/test-utils/commit/4e9f34b96ac5432cc9429aadfa07c3503dffbf15

**Comment by sebbayer** [comment]
@danielroe sorry to revive this, but even with 3.15.4 when I have a prop named `results` with `mountSuspended` I still get the warning

> [Vue warn]: Cannot mutate <script setup> binding "results" from Options API. 

A prop named `error` seems to be working though.

**Comment by nandi95** [comment]
`3.16.1` I'm getting this with a prop name `error` if I rename that, it works just fine
